### ISSUE TITLE
[Bug] When Arabic letter has a HAMZA-form reshaping throws an error

### ISSUE THREAD

**Issue by Milad-Akarie** [xclud/dart_bidi#3]
first of all, thank you for this great package. 
I've noticed that when a letter of the sentence has a HAMZA an error occurs.
I think the problem is letters with `Hamza` should be `reshaped` not decomposed into a base letter and a diacritic.

 All of these throw an out of range error
```dart
  bidi.logicalToVisual('أ');
  bidi.logicalToVisual('إ');
  bidi.logicalToVisual('ؤ');
  bidi.logicalToVisual('ئ');
```

stacktrace
```yaml
RangeError (index): Invalid value: Only valid value is 0: 1
dart:core                               List.[]
package:bidi/src/paragraph.dart 752:24  Paragraph.internalCompose
package:bidi/src/paragraph.dart 113:5   Paragraph.normalizeText
package:bidi/src/paragraph.dart 42:5    Paragraph.text=
package:bidi/src/paragraph.dart 13:10   new Paragraph
package:bidi/src/bidi.dart 73:13        splitStringToParagraphs
package:bidi/src/bidi.dart 9:16         logicalToVisual
test/arabic_test.dart 40:8              main
```

these don't throw an error  but the result is incorrect
```dart
  bidi.logicalToVisual('خطأ');
  bidi.logicalToVisual('كؤ');
  bidi.logicalToVisual('مئ');
```

**Comment by Milad-Akarie** [comment]
for example when I convert the letter 'أ'
in `getUnicodeDecompositionMapping` a decomp is returned and the code crashes,

but if I comment out the the letter mapping in `decomMapping`
` // 0x0623: [0x0627, 0x0654],`
 everything works as expected.

**Comment by Milad-Akarie** [comment]
@xclud can you help me understand why unicode normalization is needed here?

**Comment by xclud** [comment]
Hi Milad, Thank you for reporting. Please give me some time to investigate the problem. I'll let you know here.

**Comment by Milad-Akarie** [comment]
@xclud This might be related to the issue.
I think decomposed codes are never composed back because in `paragraph.dart` 

```dart
int getPairwiseComposition(int first, int second) {
    if (first < 0 || first > 0xFFFF || second < 0 || second > 0xFFFF) {
      return BidiChars.NotAChar;
    }
    return compose(first.toString() + second.toString()); // this line
  }
```
`compose`  is being called with merged code points
for example if we're processing 'أ'  
=>  compose('1575'+'1620')
and that's getting compared against utf-16 merged codes from `composeMapping` 

```dart
const Map<String, int> composeMapping = {
  '\u0020': 0x3000,
  '\u0020\u0301': 0x0384,
  '\u0020\u0303': 0x02DC,
  '\u0020\u0304': 0x00AF,
  '\u0020\u0305': 0x203E,
  '\u0020\u0306': 0x02D8,
  '\u0020\u0307': 0x02D9,
  '\u0020\u0308': 0x00A8,
   ........
}
```
and to get a match I believe we need to pass utf-16 merged codes 
`compose('\u0627\u064B')` which I couldn't find a ready to use dart converter for it.
or change `composeMapping` keys to another form.

**Comment by xclud** [comment]
Hi Milad, Thank you for providing more details. This could be the source of the problem.

Do you think `String.fromCharCodes([first, second])` will fix this, instead of `first.toString() + second.toString()`?

**Comment by xclud** [comment]
This should be fixed in version `2.0.1` now. Please open a new issue if the bug still exists.

Thank you for reporting the bug and debugging the code.

**Comment by Milad-Akarie** [comment]
@xclud Thank you very much for taking the time to fix this. I've tried it and it looks fine for now.

**Comment by xclud** [comment]
That's great to hear. I mentioned you in the CHANGELOG.MD.
