### ISSUE TITLE
re-expose  paragraph.paragraphSeparator

### ISSUE THREAD

**Issue by Milad-Akarie** [xclud/dart_bidi#5]
Hello @xclud  in your latest refractor you made   paragraph.paragraphSeparator private, and I'm using it in some package, can you please make it public again?

**Comment by xclud** [comment]
Hi Milad, Sorry for the inconvenience. This is fixed now in v2.0.5.

**Comment by Milad-Akarie** [comment]
Thank you very much for the quick response.
