### ISSUE TITLE
Using Arabic letters basic from in favor of isolated form

### ISSUE THREAD

**Issue by Milad-Akarie** [xclud/dart_bidi#6]
Hey, @xclud 
context: There are two letter forms in Arabic that render exactly the same, the basic form and the isolated form.

Notices how the following Arabic letter  LAM has the same glyph for both basic and isolated form. 
![image](https://github.com/xclud/dart_bidi/assets/55059449/1de4e638-a970-44af-b89f-bbd2dce7bc62)

currently, the algorithm maps to the isolated form which might be the right thing to do but unfortunately Arabic Google fonts seem to have a problem with this, this issue can be fixed by always mapping to the basic form when an isolated form is required. 
 
even dart seems to work with the basic form in such cases 
```dart
 final letter = 'ل';
 print(letter.codeUnits); // prints [1604]
 print(bidi.logicalToVisual(letter)); // prints [65245]
```

 I'm willing the make a PR, but do you think we should introduce this change as an optional change or just hard-code it? 
 
 P.s I'll be changing the mappings inside of `shapping_resolver._charForms`

**Comment by xclud** [comment]
Hi Milad.

Why not mapping to isolated and basic both depending on where the character is located?

**Comment by Milad-Akarie** [comment]
Hey, @xclud there isn't a specific use for the basic form, both forms are considered isolated, initial,middle and final forms will not be touched as they work as expected.

**Comment by Milad-Akarie** [comment]
@xclud any updates on this?

**Comment by xclud** [comment]
I am afraid to make such a change if it's only a problem with google fonts.

I need to make sure if it's a bug in the font or in the package.

**Comment by Milad-Akarie** [comment]
I've checked one famous Arabic Google font 'Cairo' and the glyph for the isolated letter LAM is not there, to be safe I can make it an optional flag or even a separate function so that only users who need to use the basic forms can enable it.

**Comment by xclud** [comment]
Sounds good 👌

**Comment by Milad-Akarie** [comment]
Hey @xclud I hope you're doing well.

After creating the PR we talked about above, I realized that the rendering tool should be responsible for having isolated form codes with no corresponding glyphs mapped to basic form glyphs since they're the same.

Thank you fro your time. 
I'm closing this for now.

**Comment by xclud** [comment]
Great to hear the problem is solved.
